# Generated by Django 4.2 on 2025-06-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageentry",
            name="rating",
            field=models.FloatField(default=1500),
        ),
    ]
